# Generated by Django 3.1.5 on 2022-03-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetPhotosApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFacesAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('key', models.TextField()),
            ],
        ),
    ]
